[package]
name = "lava-lamp"
version = "0.1.0"
authors = ["Vake Domen <vake.domen94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# piston = "0.52.0"
piston_window = "0.111.0"
rand = "0.7.3"